// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Configuration.Context;

#nullable disable

namespace Repository.Configuration.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220614000524_property-sync-mapping")]
    partial class propertysyncmapping
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Compacts.Settings.Users.CompactUser", b =>
                {
                    b.Property<int?>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AttachmentId");

                    b.ToView("vw_Users", "settings");
                });

            modelBuilder.Entity("Domain.Entities.BaseLogs.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs", "log");
                });

            modelBuilder.Entity("Domain.Entities.BaseLogs.LogContent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contents", "log");
                });

            modelBuilder.Entity("Domain.Entities.Files.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Attachments", "files");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Answers", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.AnswerVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.ToTable("AnswerVersion", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.AnswerVersionIssues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnswerVersionId")
                        .HasColumnType("int");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerVersionId");

                    b.HasIndex("IssueId");

                    b.ToTable("AnswerVersionIssues", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.ChecklistMaintenance.Checklist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Checklists", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.ChecklistMaintenance.ChecklistVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChecklistId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.ToTable("ChecklistVersion", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.ChecklistMaintenance.ChecklistVersionQuestions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChecklistVersionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistVersionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("ChecklistVersionQuestions", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Questions", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.Questions.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("QuestionType", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("EnableNotApply")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("RequireSelfInspection")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireValidation")
                        .HasColumnType("bit");

                    b.Property<bool>("Required")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("QuestionVersion", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersionAnswers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AnswerVersionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerVersionId");

                    b.HasIndex("QuestionVersionId");

                    b.ToTable("QuestionVersionAnswers", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersionRecommendations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("QuestionVersionId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("RecommendationVersionId");

                    b.ToTable("QuestionVersionRecommendations", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.SubQuestionVersions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("QuestionVersionId")
                        .HasColumnType("int");

                    b.Property<int>("SubQuestionVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionVersionId");

                    b.HasIndex("SubQuestionVersionId");

                    b.ToTable("SubQuestionVersions", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Issues.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Issues", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Issues.IssueTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("IssueTags", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Recommendation", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AttachmentId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId");

                    b.HasIndex("RecommendationVersionId");

                    b.ToTable("RecommendationAttachment", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationVersionStatusId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.HasIndex("RecommendationVersionStatusId");

                    b.ToTable("RecommendationVersion", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersionIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("RecommendationVersionId");

                    b.ToTable("RecommendationVersionIssues", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("RecommendationVersionStatus", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Countries.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Countries", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Inspections", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplateVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("InspectionTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspectionTemplateId");

                    b.ToTable("InspectionTemplateVersion", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplateVersionChecklists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ChecklistId")
                        .HasColumnType("int");

                    b.Property<int>("InspectionTemplateVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("InspectionTemplateVersionId");

                    b.ToTable("InspectionTemplateVersionChecklists", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplateVersionPropertyTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("InspectionTemplateVersionId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InspectionTemplateVersionId");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("InspectionTemplateVersionPropertyTypes", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("LegalEntityTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LegalEntityTypeId");

                    b.HasIndex("ParentId");

                    b.ToTable("LegalEntity", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("LegalEntityType", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntityContacts.LegalEntityContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LegalEntityContactTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LegalEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LegalEntityContactTypeId");

                    b.HasIndex("LegalEntityId");

                    b.ToTable("LegalEntityContact", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntityContacts.LegalEntityContactType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("LegalEntityContactType", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntitySyncs.LegalEntitySync", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("LegalEntitySyncStatusId")
                        .HasColumnType("int");

                    b.Property<int>("LegalEntityTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("LegalEntitySyncStatusId");

                    b.HasIndex("LegalEntityTypeId");

                    b.HasIndex("ParentId");

                    b.ToTable("LegalEntitySync", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntitySyncs.LegalEntitySyncStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("LegalEntitySyncStatus", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.PropertyCore.Properties.Property", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("LegalEntityId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LegalEntityId");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("Property", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.PropertyCore.Properties.PropertyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("PropertyType", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.PropertyCore.PropertySyncs.PropertySync", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("LegalEntityId")
                        .HasColumnType("int");

                    b.Property<int>("PropertySyncStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LegalEntityId");

                    b.HasIndex("PropertySyncStatusId");

                    b.HasIndex("PropertyTypeId");

                    b.ToTable("PropertySync", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.PropertyCore.PropertySyncs.PropertySyncStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("PropertySyncStatus", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Users", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Users.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("UserProfile", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Users.UsersLegalEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LegalEntityId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LegalEntityId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersLegalEntities", "settings");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Users.UsersProfiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UsersProfiles", "settings");
                });

            modelBuilder.Entity("Domain.Compacts.Settings.Users.CompactUser", b =>
                {
                    b.HasOne("Domain.Entities.Files.Attachment", "Avatar")
                        .WithMany()
                        .HasForeignKey("AttachmentId");

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("Domain.Entities.BaseLogs.Log", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.BaseLogs.LogContent", b =>
                {
                    b.HasOne("Domain.Entities.BaseLogs.Log", "Log")
                        .WithOne("LogContent")
                        .HasForeignKey("Domain.Entities.BaseLogs.LogContent", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");
                });

            modelBuilder.Entity("Domain.Entities.Files.Attachment", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Files.Bucket", "Bucket", b1 =>
                        {
                            b1.Property<int>("AttachmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Bucket");

                            b1.HasKey("AttachmentId");

                            b1.ToTable("Attachments", "files");

                            b1.WithOwner()
                                .HasForeignKey("AttachmentId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Files.ContentType", "ContentType", b1 =>
                        {
                            b1.Property<int>("AttachmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("ContentType");

                            b1.HasKey("AttachmentId");

                            b1.ToTable("Attachments", "files");

                            b1.WithOwner()
                                .HasForeignKey("AttachmentId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Files.FileName", "FileName", b1 =>
                        {
                            b1.Property<int>("AttachmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("varchar(250)")
                                .HasColumnName("FileName");

                            b1.HasKey("AttachmentId");

                            b1.ToTable("Attachments", "files");

                            b1.WithOwner()
                                .HasForeignKey("AttachmentId");
                        });

                    b.OwnsOne("Domain.ValueObjects.General.GuId", "Guid", b1 =>
                        {
                            b1.Property<int>("AttachmentId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("varchar(36)")
                                .HasColumnName("GuId");

                            b1.HasKey("AttachmentId");

                            b1.ToTable("Attachments", "files");

                            b1.WithOwner()
                                .HasForeignKey("AttachmentId");
                        });

                    b.Navigation("Bucket")
                        .IsRequired();

                    b.Navigation("ContentType")
                        .IsRequired();

                    b.Navigation("FileName")
                        .IsRequired();

                    b.Navigation("Guid")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.Answer", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.AnswerVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.AnswerVersion", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.Answer", "Answer")
                        .WithMany("AnswerVersions")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.General.Description", "Description", b1 =>
                        {
                            b1.Property<int>("AnswerVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Description");

                            b1.HasKey("AnswerVersionId");

                            b1.ToTable("AnswerVersion", "settings");

                            b1.WithOwner()
                                .HasForeignKey("AnswerVersionId");
                        });

                    b.Navigation("Answer");

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.AnswerVersionIssues", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.AnswerVersion", "AnswerVersion")
                        .WithMany("AnswerVersionIssues")
                        .HasForeignKey("AnswerVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Checklist.RecommendationsCore.Issues.Issue", "Issue")
                        .WithMany("AnswerVersionIssues")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnswerVersion");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.ChecklistMaintenance.Checklist", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.ChecklistMaintenance.ChecklistVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.ChecklistMaintenance.ChecklistVersion", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.ChecklistMaintenance.Checklist", "Checklist")
                        .WithMany("ChecklistVersions")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Settings.Checklist.QuestionsMaintenance.Questions.Key", "Key", b1 =>
                        {
                            b1.Property<int>("ChecklistVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Key");

                            b1.HasKey("ChecklistVersionId");

                            b1.ToTable("ChecklistVersion", "settings");

                            b1.WithOwner()
                                .HasForeignKey("ChecklistVersionId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Inspections.InspectionMaintenance.InspectionTemplates.Title", "Title", b1 =>
                        {
                            b1.Property<int>("ChecklistVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Title");

                            b1.HasKey("ChecklistVersionId");

                            b1.ToTable("ChecklistVersion", "settings");

                            b1.WithOwner()
                                .HasForeignKey("ChecklistVersionId");
                        });

                    b.Navigation("Checklist");

                    b.Navigation("Key")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.ChecklistMaintenance.ChecklistVersionQuestions", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.ChecklistMaintenance.ChecklistVersion", "ChecklistVersion")
                        .WithMany("ChecklistVersionQuestions")
                        .HasForeignKey("ChecklistVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Checklist.QuestionMaintenance.Question", "Question")
                        .WithMany("ChecklistVersionQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChecklistVersion");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.Question", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.Questions.QuestionType", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.EnumDescription", "Description", b1 =>
                        {
                            b1.Property<int>("QuestionTypeId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Description");

                            b1.HasKey("QuestionTypeId");

                            b1.ToTable("QuestionType", "settings");

                            b1.WithOwner()
                                .HasForeignKey("QuestionTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersion", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.QuestionMaintenance.Question", "Question")
                        .WithMany("QuestionVersions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Checklist.QuestionMaintenance.Questions.QuestionType", "QuestionType")
                        .WithMany("QuestionVersions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.General.Description", "Description", b1 =>
                        {
                            b1.Property<int>("QuestionVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Description");

                            b1.HasKey("QuestionVersionId");

                            b1.ToTable("QuestionVersion", "settings");

                            b1.WithOwner()
                                .HasForeignKey("QuestionVersionId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Checklist.QuestionsMaintenance.Questions.Key", "Key", b1 =>
                        {
                            b1.Property<int>("QuestionVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Key");

                            b1.HasKey("QuestionVersionId");

                            b1.ToTable("QuestionVersion", "settings");

                            b1.WithOwner()
                                .HasForeignKey("QuestionVersionId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Checklist.QuestionsMaintenance.Questions.Tips", "Tips", b1 =>
                        {
                            b1.Property<int>("QuestionVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Tips");

                            b1.HasKey("QuestionVersionId");

                            b1.ToTable("QuestionVersion", "settings");

                            b1.WithOwner()
                                .HasForeignKey("QuestionVersionId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Key")
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("QuestionType");

                    b.Navigation("Tips")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersionAnswers", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.AnswerVersion", "AnswerVersion")
                        .WithMany("QuestionVersionAnswers")
                        .HasForeignKey("AnswerVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersion", "QuestionVersion")
                        .WithMany("QuestionVersionAnswers")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnswerVersion");

                    b.Navigation("QuestionVersion");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersionRecommendations", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersion", "QuestionVersion")
                        .WithMany("QuestionVersionRecommendations")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersion", "RecommendationVersion")
                        .WithMany("QuestionVersionRecommendations")
                        .HasForeignKey("RecommendationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuestionVersion");

                    b.Navigation("RecommendationVersion");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.SubQuestionVersions", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersion", "QuestionVersion")
                        .WithMany("SubQuestionVersions")
                        .HasForeignKey("QuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersion", "SubQuestionVersion")
                        .WithMany("SubQuestionVersionsSubQuestionVersions")
                        .HasForeignKey("SubQuestionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("QuestionVersion");

                    b.Navigation("SubQuestionVersion");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Issues.Issue", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.Description", "Description", b1 =>
                        {
                            b1.Property<int>("IssueId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Description");

                            b1.HasKey("IssueId");

                            b1.ToTable("Issues", "settings");

                            b1.WithOwner()
                                .HasForeignKey("IssueId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Issues.IssueTag", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.RecommendationsCore.Issues.Issue", "Issue")
                        .WithMany("Tags")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Settings.Checklist.RecommendationsCore.Issues.Tag", "Tag", b1 =>
                        {
                            b1.Property<int>("IssueTagId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Tag");

                            b1.HasKey("IssueTagId");

                            b1.ToTable("IssueTags", "settings");

                            b1.WithOwner()
                                .HasForeignKey("IssueTagId");
                        });

                    b.Navigation("Issue");

                    b.Navigation("Tag")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.Recommendation", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationAttachment", b =>
                {
                    b.HasOne("Domain.Entities.Files.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersion", "RecommendationVersion")
                        .WithMany("RecommendationAttachments")
                        .HasForeignKey("RecommendationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attachment");

                    b.Navigation("RecommendationVersion");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersion", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.Recommendation", "Recommendation")
                        .WithMany("RecommendationVersions")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersionStatus", "RecommendationVersionStatus")
                        .WithMany("RecommendationVersions")
                        .HasForeignKey("RecommendationVersionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.General.Description", "Description", b1 =>
                        {
                            b1.Property<int>("RecommendationVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Description");

                            b1.HasKey("RecommendationVersionId");

                            b1.ToTable("RecommendationVersion", "settings");

                            b1.WithOwner()
                                .HasForeignKey("RecommendationVersionId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Checklist.RecommendationsCore.Recommendations.DueDateText", "DueDateText", b1 =>
                        {
                            b1.Property<int>("RecommendationVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("DueDateText");

                            b1.HasKey("RecommendationVersionId");

                            b1.ToTable("RecommendationVersion", "settings");

                            b1.WithOwner()
                                .HasForeignKey("RecommendationVersionId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Checklist.RecommendationsCore.Recommendations.Title", "Title", b1 =>
                        {
                            b1.Property<int>("RecommendationVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Title");

                            b1.HasKey("RecommendationVersionId");

                            b1.ToTable("RecommendationVersion", "settings");

                            b1.WithOwner()
                                .HasForeignKey("RecommendationVersionId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("DueDateText")
                        .IsRequired();

                    b.Navigation("Recommendation");

                    b.Navigation("RecommendationVersionStatus");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersionIssue", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.RecommendationsCore.Issues.Issue", "Issue")
                        .WithMany("RecommendationVersionIssues")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersion", "RecommendationVersion")
                        .WithMany("RecommendationVersionIssues")
                        .HasForeignKey("RecommendationVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("RecommendationVersion");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersionStatus", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.EnumDescription", "Description", b1 =>
                        {
                            b1.Property<int>("RecommendationVersionStatusId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Description");

                            b1.HasKey("RecommendationVersionStatusId");

                            b1.ToTable("RecommendationVersionStatus", "settings");

                            b1.WithOwner()
                                .HasForeignKey("RecommendationVersionStatusId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Countries.Country", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.Description", "Description", b1 =>
                        {
                            b1.Property<int>("CountryId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Description");

                            b1.HasKey("CountryId");

                            b1.ToTable("Countries", "settings");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Countries.Lang", "Lang", b1 =>
                        {
                            b1.Property<int>("CountryId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("varchar(5)")
                                .HasColumnName("Lang");

                            b1.HasKey("CountryId");

                            b1.ToTable("Countries", "settings");

                            b1.WithOwner()
                                .HasForeignKey("CountryId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Lang")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplate", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplateVersion", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplateVersion", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplate", "InspectionTemplate")
                        .WithMany("InspectionTemplateVersions")
                        .HasForeignKey("InspectionTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Settings.Inspections.InspectionMaintenance.InspectionTemplates.Title", "Title", b1 =>
                        {
                            b1.Property<int>("InspectionTemplateVersionId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("varchar(255)")
                                .HasColumnName("Title");

                            b1.HasKey("InspectionTemplateVersionId");

                            b1.ToTable("InspectionTemplateVersion", "settings");

                            b1.WithOwner()
                                .HasForeignKey("InspectionTemplateVersionId");
                        });

                    b.Navigation("InspectionTemplate");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplateVersionChecklists", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Checklist.ChecklistMaintenance.Checklist", "Checklist")
                        .WithMany("InspectionTemplateVersionChecklists")
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplateVersion", "InspectionTemplateVersion")
                        .WithMany("InspectionTemplateVersionChecklists")
                        .HasForeignKey("InspectionTemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("InspectionTemplateVersion");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplateVersionPropertyTypes", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplateVersion", "InspectionTemplateVersion")
                        .WithMany("InspectionTemplateVersionPropertyTypes")
                        .HasForeignKey("InspectionTemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.PropertyCore.Properties.PropertyType", "PropertyType")
                        .WithMany("InspectionTemplateVersionPropertyTypes")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InspectionTemplateVersion");

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntity", b =>
                {
                    b.HasOne("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntityType", "LegalEntityType")
                        .WithMany("LegalEntities")
                        .HasForeignKey("LegalEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntity", "Parent")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Domain.ValueObjects.General.CodeEntity", "CodeEntity", b1 =>
                        {
                            b1.Property<int>("LegalEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("CodeEntity");

                            b1.HasKey("LegalEntityId");

                            b1.ToTable("LegalEntity", "settings");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Entities.Name", "Name", b1 =>
                        {
                            b1.Property<int>("LegalEntityId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Name");

                            b1.HasKey("LegalEntityId");

                            b1.ToTable("LegalEntity", "settings");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityId");
                        });

                    b.Navigation("CodeEntity")
                        .IsRequired();

                    b.Navigation("LegalEntityType");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntityType", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.EnumDescription", "Description", b1 =>
                        {
                            b1.Property<int>("LegalEntityTypeId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Description");

                            b1.HasKey("LegalEntityTypeId");

                            b1.ToTable("LegalEntityType", "settings");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntityContacts.LegalEntityContact", b =>
                {
                    b.HasOne("Domain.Entities.Settings.LegalEntityCore.LegalEntityContacts.LegalEntityContactType", "LegalEntityContactType")
                        .WithMany("LegalEntityContacts")
                        .HasForeignKey("LegalEntityContactTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntity", "LegalEntity")
                        .WithMany("LegalEntityContacts")
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.General.Email", "Email", b1 =>
                        {
                            b1.Property<int>("LegalEntityContactId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Email");

                            b1.HasKey("LegalEntityContactId");

                            b1.ToTable("LegalEntityContact", "settings");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityContactId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Entities.Name", "Name", b1 =>
                        {
                            b1.Property<int>("LegalEntityContactId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Name");

                            b1.HasKey("LegalEntityContactId");

                            b1.ToTable("LegalEntityContact", "settings");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityContactId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("LegalEntity");

                    b.Navigation("LegalEntityContactType");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntityContacts.LegalEntityContactType", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.EnumDescription", "Description", b1 =>
                        {
                            b1.Property<int>("LegalEntityContactTypeId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Description");

                            b1.HasKey("LegalEntityContactTypeId");

                            b1.ToTable("LegalEntityContactType", "settings");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityContactTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntitySyncs.LegalEntitySync", b =>
                {
                    b.HasOne("Domain.Entities.Settings.LegalEntityCore.LegalEntitySyncs.LegalEntitySyncStatus", null)
                        .WithMany("LegalEntitySyncs")
                        .HasForeignKey("LegalEntitySyncStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntityType", "LegalEntityType")
                        .WithMany("LegalEntitySyncs")
                        .HasForeignKey("LegalEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.LegalEntityCore.LegalEntitySyncs.LegalEntitySync", "Parent")
                        .WithMany("Childrens")
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Domain.ValueObjects.General.CodeEntity", "CodeEntity", b1 =>
                        {
                            b1.Property<int>("LegalEntitySyncId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("CodeEntity");

                            b1.HasKey("LegalEntitySyncId");

                            b1.ToTable("LegalEntitySync", "settings");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntitySyncId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Entities.Name", "Name", b1 =>
                        {
                            b1.Property<int>("LegalEntitySyncId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Name");

                            b1.HasKey("LegalEntitySyncId");

                            b1.ToTable("LegalEntitySync", "settings");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntitySyncId");
                        });

                    b.Navigation("CodeEntity")
                        .IsRequired();

                    b.Navigation("LegalEntityType");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntitySyncs.LegalEntitySyncStatus", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.EnumDescription", "Description", b1 =>
                        {
                            b1.Property<int>("LegalEntitySyncStatusId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Description");

                            b1.HasKey("LegalEntitySyncStatusId");

                            b1.ToTable("LegalEntitySyncStatus", "settings");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntitySyncStatusId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.PropertyCore.Properties.Property", b =>
                {
                    b.HasOne("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntity", "LegalEntity")
                        .WithMany("Properties")
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.PropertyCore.Properties.PropertyType", "PropertyType")
                        .WithMany("Properties")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Settings.Properties.Code", "Code", b1 =>
                        {
                            b1.Property<int>("PropertyId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Code");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Property", "settings");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Properties.Name", "Name", b1 =>
                        {
                            b1.Property<int>("PropertyId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Name");

                            b1.HasKey("PropertyId");

                            b1.ToTable("Property", "settings");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.Navigation("Code");

                    b.Navigation("LegalEntity");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("Domain.Entities.Settings.PropertyCore.Properties.PropertyType", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.EnumDescription", "Description", b1 =>
                        {
                            b1.Property<int>("PropertyTypeId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Description");

                            b1.HasKey("PropertyTypeId");

                            b1.ToTable("PropertyType", "settings");

                            b1.WithOwner()
                                .HasForeignKey("PropertyTypeId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.PropertyCore.PropertySyncs.PropertySync", b =>
                {
                    b.HasOne("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntity", "LegalEntity")
                        .WithMany("PropertySyncs")
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.PropertyCore.PropertySyncs.PropertySyncStatus", null)
                        .WithMany("PropertySyncs")
                        .HasForeignKey("PropertySyncStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.PropertyCore.Properties.PropertyType", "PropertyType")
                        .WithMany("PropertySyncs")
                        .HasForeignKey("PropertyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Settings.Properties.Code", "Code", b1 =>
                        {
                            b1.Property<int>("PropertySyncId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("Code");

                            b1.HasKey("PropertySyncId");

                            b1.ToTable("PropertySync", "settings");

                            b1.WithOwner()
                                .HasForeignKey("PropertySyncId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Properties.Name", "Name", b1 =>
                        {
                            b1.Property<int>("PropertySyncId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Name");

                            b1.HasKey("PropertySyncId");

                            b1.ToTable("PropertySync", "settings");

                            b1.WithOwner()
                                .HasForeignKey("PropertySyncId");
                        });

                    b.Navigation("Code");

                    b.Navigation("LegalEntity");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("PropertyType");
                });

            modelBuilder.Entity("Domain.Entities.Settings.PropertyCore.PropertySyncs.PropertySyncStatus", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.EnumDescription", "Description", b1 =>
                        {
                            b1.Property<int>("PropertySyncStatusId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Description");

                            b1.HasKey("PropertySyncStatusId");

                            b1.ToTable("PropertySyncStatus", "settings");

                            b1.WithOwner()
                                .HasForeignKey("PropertySyncStatusId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Users.User", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "settings");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Users.Name", "Name", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Name");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "settings");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Settings.Users.UId", "UId", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("varchar(64)")
                                .HasColumnName("UId");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "settings");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("UId");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Users.UserProfile", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.General.EnumDescription", "Description", b1 =>
                        {
                            b1.Property<int>("UserProfileId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("Description");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("UserProfile", "settings");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Description")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Settings.Users.UsersLegalEntities", b =>
                {
                    b.HasOne("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntity", "LegalEntity")
                        .WithMany("UsersLegalEntities")
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Users.User", "User")
                        .WithMany("UsersLegalEntities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LegalEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Users.UsersProfiles", b =>
                {
                    b.HasOne("Domain.Entities.Settings.Users.User", "User")
                        .WithMany("UsersProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Settings.Users.UserProfile", "UserProfile")
                        .WithMany("UsersProfiles")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Domain.Entities.BaseLogs.Log", b =>
                {
                    b.Navigation("LogContent");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.Answer", b =>
                {
                    b.Navigation("AnswerVersions");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.AnswerMaintenance.Answers.AnswerVersion", b =>
                {
                    b.Navigation("AnswerVersionIssues");

                    b.Navigation("QuestionVersionAnswers");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.ChecklistMaintenance.Checklist", b =>
                {
                    b.Navigation("ChecklistVersions");

                    b.Navigation("InspectionTemplateVersionChecklists");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.ChecklistMaintenance.ChecklistVersion", b =>
                {
                    b.Navigation("ChecklistVersionQuestions");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.Question", b =>
                {
                    b.Navigation("ChecklistVersionQuestions");

                    b.Navigation("QuestionVersions");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.Questions.QuestionType", b =>
                {
                    b.Navigation("QuestionVersions");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.QuestionMaintenance.QuestionVersion", b =>
                {
                    b.Navigation("QuestionVersionAnswers");

                    b.Navigation("QuestionVersionRecommendations");

                    b.Navigation("SubQuestionVersions");

                    b.Navigation("SubQuestionVersionsSubQuestionVersions");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Issues.Issue", b =>
                {
                    b.Navigation("AnswerVersionIssues");

                    b.Navigation("RecommendationVersionIssues");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.Recommendation", b =>
                {
                    b.Navigation("RecommendationVersions");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersion", b =>
                {
                    b.Navigation("QuestionVersionRecommendations");

                    b.Navigation("RecommendationAttachments");

                    b.Navigation("RecommendationVersionIssues");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Checklist.RecommendationsCore.Recommendations.RecommendationVersionStatus", b =>
                {
                    b.Navigation("RecommendationVersions");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplate", b =>
                {
                    b.Navigation("InspectionTemplateVersions");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Inspections.InspectionMaintenance.InspectionTemplates.InspectionTemplateVersion", b =>
                {
                    b.Navigation("InspectionTemplateVersionChecklists");

                    b.Navigation("InspectionTemplateVersionPropertyTypes");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntity", b =>
                {
                    b.Navigation("Childrens");

                    b.Navigation("LegalEntityContacts");

                    b.Navigation("Properties");

                    b.Navigation("PropertySyncs");

                    b.Navigation("UsersLegalEntities");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntities.LegalEntityType", b =>
                {
                    b.Navigation("LegalEntities");

                    b.Navigation("LegalEntitySyncs");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntityContacts.LegalEntityContactType", b =>
                {
                    b.Navigation("LegalEntityContacts");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntitySyncs.LegalEntitySync", b =>
                {
                    b.Navigation("Childrens");
                });

            modelBuilder.Entity("Domain.Entities.Settings.LegalEntityCore.LegalEntitySyncs.LegalEntitySyncStatus", b =>
                {
                    b.Navigation("LegalEntitySyncs");
                });

            modelBuilder.Entity("Domain.Entities.Settings.PropertyCore.Properties.PropertyType", b =>
                {
                    b.Navigation("InspectionTemplateVersionPropertyTypes");

                    b.Navigation("Properties");

                    b.Navigation("PropertySyncs");
                });

            modelBuilder.Entity("Domain.Entities.Settings.PropertyCore.PropertySyncs.PropertySyncStatus", b =>
                {
                    b.Navigation("PropertySyncs");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Users.User", b =>
                {
                    b.Navigation("UsersLegalEntities");

                    b.Navigation("UsersProfiles");
                });

            modelBuilder.Entity("Domain.Entities.Settings.Users.UserProfile", b =>
                {
                    b.Navigation("UsersProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
